name: ips
version: "0.2.0"
config-version: 2
profile: ips

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: target
clean-targets: ["target", "logs"]

flags:
  send_anonymous_usage_stats: false

models:
  ips:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table
